x-python-base: &python_base
  tty: true
  env_file:
    - ../.env
  # volumes:
  #   - ../:/src # Mount entire project for live code changes
  # working_dir: /src

services:
  python310:
    <<: *python_base
    image: iloveimg-python310
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        PYTHON_VERSION: "3.10"
    container_name: iloveimg-python310

  python311:
    <<: *python_base
    image: iloveimg-python311
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        PYTHON_VERSION: "3.11"
    container_name: iloveimg-python311

  python312:
    <<: *python_base
    image: iloveimg-python312
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        PYTHON_VERSION: "3.12"
    container_name: iloveimg-python312

  python313:
    <<: *python_base
    image: iloveimg-python313
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        PYTHON_VERSION: "3.13"
    container_name: iloveimg-python313

  python314:
    <<: *python_base
    image: iloveimg-python314
    build:
      context: ../
      dockerfile: .docker/Dockerfile
      args:
        PYTHON_VERSION: "3.14"
    container_name: iloveimg-python314
